kondicionery/urls.py
from django.urls import path

from kondicionery import views

app_name = 'kondicionery'

urlpatterns = [
    path('', views.kondicionery, name='index'),
    path('<slug:category_slug>/', views.subitem, name='subitem'),
    path('/<slug:products_slug>/', views.cunit, name='cunit'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('<slug:navbar_slug>', views.navbar, name='nav'),
]

obogrevateli/urls.py
from django.urls import path

from obogrevateli import views

app_name = 'obogrevateli'

urlpatterns = [
    path('', views.obogrevateli, name='index'),
    path('<slug:category_slug>/', views.subitem, name='subitem'),
    path('hunit/', views.hunit, name='hunit'),
]

profclimatorg/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static

from profclimatorg import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('kondicionery/', include('kondicionery.urls', namespace='kondicionery')),
    path('ventilyaciya/', include('ventilyacia.urls', namespace='ventilyacia')),
    path('obogrevateli/', include('obogrevateli.urls', namespace='obogrevateli')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventilyacia/urls.py
from django.urls import path

from ventilyacia import views

app_name = 'ventilyacia'

urlpatterns = [
    path('', views.ventilyacia, name='index'),
    path('vunit/', views.vunit, name='vunit'),
]

main/models.py
from django.db import models

# Create your models here.
class Navbar(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название') 
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    code = models.TextField(blank=True, null=True,verbose_name='code')
    title = models.CharField(max_length=150, unique=True, verbose_name='Титульник')

    class Meta:
        db_table = 'navbar'
        verbose_name = 'Навигацию'
        verbose_name_plural = 'Навигация'

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render

from kondicionery.models import Manuf

from main.models import Navbar
from obogrevateli.models import Manuf_Heat

def index(request):

    navbar = Navbar.objects.all()
    manuf = Manuf.objects.all()
    manuf2 = Manuf_Heat.objects.all()

    data = {
        'title' : 'Климатические системы и оборудования',
        'navbar' : navbar,
        'manuf' : manuf,
        'manuf2' : manuf2,
    }

    return render(request, 'main/index.html', data)

def navbar(request, navbar_slug):

    nav = Navbar.objects.get(slug=navbar_slug)
    navbar = Navbar.objects.all()

    data = {
        'slug' : nav,
        'navbar' : navbar
    }
    return render(request, 'main/nav_other.html', data)

main/templates/main/blocks/button.html
<div id="button-pos">
  <div id="button-up" title="В начало">
    <div class="typcn typcn-arrow-up"></div>
  </div>
  <div id="button-down" title="В конец">
    <div class="typcn typcn-arrow-down"></div>
  </div>
</div>

main/templates/main/blocks/favicon.html
{% load static %}

<link rel="shortcut icon" href="{% static "icons/favicon.ico" %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
<link rel="icon" type="image/png" sizes="132x32" href="{% static "icons/favicon-32x32.png" %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static "icons/favicon-96x96.png" %}">
<link rel="icon" type="image/png" sizes="120x120" href="{% static "icons/favicon-120x120.png" %}">
<link rel="icon" sizes="any" type="image/svg+xml" href="{% static "icons/favicon.svg" %}">
<link rel="apple-touch-icon" sizes="180x180" href="{%static "icons/apple-touch-icon.png"%}">
<!--link manifest-->
<link rel="mask-icon" href="{% static "icons/safari-pinned-tab.svg" %}" color="#5bbad5">

main/templates/main/blocks/footer.html
{% load static %}

<footer>
  <div id="bottom">
    <div id="view-mode">
      <div id="view-mode-desktop" data-mode="desktop">
        <i class="typcn typcn-device-desktop"></i> Переключиться на полную
        версию
      </div>
      <div id="view-mode-mobile" data-mode="mobile">
        <i class="typcn typcn-device-tablet"></i> Переключиться на мобильную
        версию
      </div>
      <div id="view-mode-auto" data-mode="">Автоопределение версии</div>
    </div>
    <div id="footer-contact">
      <div id="footer-contact-org">
        ООО «Профклимат»
      </div>
      <div id="footer-contact-phone">
        <a href="tel:+78005503628" rel="nofollow">+7 (800) 550-36-28</a>
        <br>
        <a href="tel:+79219041899" rel="nofollow">+7 (921) 904-18-99</a>
        <br>
        <a href="tel:+78129041899" rel="nofollow">+7 (812) 904-18-99</a>
      </div>
      <div style="margin-left: 3pt">
        <span style="font-size: 130%">&#9993;</span>
        <span style="vertical-align: 0.2em"
          >email:
          <a
            href="mailto:info@profclimatspb.ru"
            style="text-decoration: none; color: #eee"
            >info@profclimatspb.ru</a
          ></span
        >
      </div>
      <div id="footer-contact-address">
        195271, город Санкт-Петербург, Бестужевская улица, дом 10, ТЦ Бестужевский, помещение 245
      </div>
    </div>
    <div id="footer-social">
      <a id="footer-social-vk" href="https://vk.com/club135867292" rel="nofollow" title="«Профклимат СПб» во ВКонтакте"></a>
      <!--a id="contact-social-vk" href="https://vk.com/profclimatspb" title="«Профклимат СПб» во ВКонтакте"></a-->
      <a id="footer-social-twitter" href="https://twitter.com/ProfclimatSpb" rel="nofollow" title="«Профклимат СПб» в Twitter"></a>
      <!--TMPL_IF NAME='viber'-->
      <a
        id="footer-viber"
        href="viber://chat?number=+79219041899" rel="nofollow" title="Viber"><img src="{% static "/images/viber-b.png" %}" alt="viber"/></a>
      <!--/TMPL_IF-->
      <!--TMPL_IF NAME='whatsapp'-->
      <a
        id="footer-whatsapp"
        href="whatsapp://send?phone=+79219041899"
        rel="nofollow"
        title="Whatsapp"
        ><img src="{% static "/images/whatsapp-b.png" %}" alt="whatsapp"
      /></a>
      <!--/TMPL_IF-->
    </div>
    <div id="footer-gallery">
      <div>Фотогалереи:</div>
      <a href="/kondicionery/galereya"
        >Различные варианты монтажей кондиционеров</a
      >
    </div>
    <div id="footer-menu">
      <!--TMPL_LOOP NAME="footer-menu"-->
      <a href="/podbor">Подбор</a>
      <a href="/pub">Статьи</a>
      <!--/TMPL_LOOP-->
    </div>
    <div id="copy">
      <a href="https://appfox.ru/" target="_blank">Продвижение сайтов - Appfox.ru</a>
      © s1802.ru, 2013-22г; ver. 2.2.3
      <!--TMPL_VAR NAME="COPY"-->
      <script>
        var _tmr = _tmr || [];
        _tmr.push({id: "2701390", type: "pageView", start: (new Date()).getTime()});
        (function (d, w, id) {
          if (d.getElementById(id)) return;
          var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
          ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
          var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
          if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
        })(document, window, "topmailru-code");
        </script>
        <noscript><div style="position:absolute;left:-10000px;">
          <img src="//top-fwz1.mail.ru/counter?id=2701390;js=na" height="1" width="1" alt="Рейтинг@Mail.ru">
          </div>
        </noscript>
        <div id="ext-links">
          <div id="ext-links-items">
            <!-- begin of Top100 code -->
            <script id="top100Counter-1" src="https://counter.rambler.ru/top100.jcn?4438770"></script>
            <noscript>
            <a href="http://top100.rambler.ru/navi/4438770/" rel="nofollow">
            <img src="https://counter.rambler.ru/top100.cnt?4438770" alt="Rambler's Top100" >
            </a>
            </noscript>
            <!-- end of Top100 code -->
            <!--LiveInternet logo--><a href="//www.liveinternet.ru/click" rel="nofollow" target="_blank"><img src="//counter.yadro.ru/logo?52.10" title="LiveInternet: показано число просмотров и посетителей за 24 часа" alt="LiveInternet" width="88" height="31"></a><!--/LiveInternet-->
            <a href="https://ru.megaindex.com/tr/info?domain=profclimatspb.ru" target="_blank"><img src="https://ru.megaindex.com/tr/profclimatspb.ru.png" alt="MegaIndex Trust Rank" border="0"></a>
          </div>
        </div>
        <script>(function(d, t, p) {var j = d.createElement(t); j.async = true; j.type = "text/javascript";j.src = ("https:" == p ? "https:" : "http:") + "//stat.sputnik.ru/cnt.js";;var s = d.getElementsByTagName(t)[0]; s.parentNode.insertBefore(j, s);})(document, "script", document.location.protocol);</script>
        <script>var _qevents = _qevents || [];(function() {var elem = document.createElement('script');elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";elem.async = true;elem.type = "text/javascript";var scpt = document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem, scpt);})();_qevents.push({qacct:"p-gyT1XqPqT_H21"});</script>
        <!--TMPL_INCLUDE NAME="../counters.html"-->
    </div>
    <div class="clr"></div>
  </div>
  <div itemscope itemtype="http://schema.org/Organization">
    <meta itemprop="name" content="ООО «ПрофКлимат»" />
    <link itemprop="url" href="https://profclimatspb.ru" />
    <link itemprop="image" href="https://profclimatspb.ru/images/logo.jpg" />
    <meta itemprop="description" content="Продажа, установка и обслуживание климатических систем в Санкт-Петербурге и Ленинградской области."/>
    <link itemprop="sameAs" href="https://vk.com/club135867292" />
    <link itemprop="sameAs" href="https://twitter.com/ProfclimatSpb" />
    <meta itemprop="telephone" content="+7 812 904-18-98" />
    <meta itemprop="email" content="info@profclimatspb.ru" />
    <div
      itemprop="address"
      itemscope
      itemtype="http://schema.org/PostalAddress"
    >
      <meta
        itemprop="streetAddress"
        content="Бестужевская улица, дом 10 литер а, помещение 5н к85 л241"
      />
      <meta itemprop="addressLocality" content="Санкт-Петербург" />
      <meta itemprop="postalCode" content="197101" />
    </div>
  </div>
</footer>
{% comment %} <div id="basket">
  <a href="/basket" title="Открыть корзину">
    <!--span class="char-m-ico typcn typcn-shopping-cart"></span-->
    <span id="basket-info">Пусто</span>
  </a>
</div> {% endcomment %}
<div id="_running" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 9999;">
  <div style="position: absolute; top: 50%; left: 50%; z-index: 9990">
    <img src="{% static "/images/running.gif"%}" alt="Подождите, идет загрузка..." />
  </div>
  <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 9999; background-color: #aaa; opacity: 0.5;"></div>
</div>

main/templates/main/blocks/header.html
<div id="header">
  <!--div id="header-title" style="background-color:#4c9ed9;"-->
  <div id="header-title">
    <a href="/" title="На главную">
      <div id="header-title-logo" style="width: 180pt; height: 64pt">
        <!-- img src="/images/ps2.png" alt="ПрофКлимат СПб" style="position: absolute; top:-4pt;left:0pt;height:85pt;opacity: 0.7;font-weight: 800;"-->
        <div
          style="
            position: absolute;
            font-size: 54pt;
            color: #f08080;
            top: -8pt;
            left: 12pt;
          "
          class="typcn typcn-weather-sunny"
        ></div>
        <div
          style="
            position: absolute;
            font-size: 54pt;
            color: #87cefa;
            top: 8pt;
            left: -9pt;
          "
          class="typcn typcn-weather-snow"
        ></div>
        <div
          style="
            position: absolute;
            font-size: 18pt;
            color: #4c9ed9;
            top: 8pt;
            left: 64pt;
            font-family: Geneva, Arial, Helvetica, sans-serif;
            text-align: right;
          "
        >
          ПрофКлимат<br />СПб
        </div>
      </div>
    </a>
    <div id="header-title-title"><!--TMPL_VAR NAME="header-title-title"--></div>
    <div class="clr"></div>
  </div>
  <div id="header-action">
    <!--TMPL_INCLUDE NAME="action-min.html"-->
  </div>
  <div
    id="view-mode"
    data-mode="mobile"
    title="Переключиться к мобильному виду"
  ></div>
  <div id="header-contacts">
    <div>
      <div id="header-contacts-phones">
        <!--TMPL_LOOP NAME="contacts-phones"-->
        <a href="tel:+78005503628" rel="nofollow"
          ><!--TMPL_VAR NAME='no'-->+7 (800) 550-36-28</a
        >
        <a href="tel:+78129041899" rel="nofollow"
          ><!--TMPL_VAR NAME='no'-->+7 (812) 904-18-99</a
        >
        <a href="tel:+79219041899" rel="nofollow"
          ><!--TMPL_VAR NAME='no'-->+7 (921) 904-18-99</a
        >
        <!--/TMPL_LOOP-->
      </div>
      <div id="header-contacts-calls">
        <!--TMPL_IF NAME='viber'-->
        <a
          id="viber"
          href="viber://chat?number=+79219041899"
          rel="nofollow"
          title="Viber"
        ></a>
        <!--/TMPL_IF-->
        <!--TMPL_IF NAME='whatsapp'-->
        <a
          id="whatsapp"
          href="whatsapp://send?phone=+79219041899"
          rel="nofollow"
          title="Whatsapp"
        ></a>
        <!--/TMPL_IF-->
      </div>
    </div>
    <a id="callback" href="/callback">Заказать обратный звонок</a>
  </div>
  <div id="header-schedule">
    <!--TMPL_LOOP NAME="contacts-schedule"-->
    <!--TMPL_IF NAME="to"-->
    <!--TMPL_IF NAME="end"-->
    <div style="margin-top: 0.3em">
      <!--TMPL_VAR NAME="from"-->пн-чт<!--TMPL_VAR NAME="to"-->:&nbsp;<!--TMPL_VAR NAME="begin"-->10:00-20:00<!--TMPL_VAR NAME="end"-->
    </div>
    <!--TMPL_ELSE-->
    <div style="margin-top: 0.3em">
      <!--TMPL_VAR NAME="from"-->пт<!--TMPL_VAR NAME="to"-->:&nbsp;<!--TMPL_VAR NAME="begin"-->11:00-18:30
    </div>
    <!--/TMPL_IF-->
    <!--TMPL_ELSE-->
    <!--TMPL_IF NAME="end"-->
    <div style="margin-top: 0.3em">
      <!--TMPL_VAR NAME="from"-->сб-вс:&nbsp;<!--TMPL_VAR NAME="begin"-->выходной
    </div>
    <!--TMPL_ELSE-->
    <!--/TMPL_IF-->
    <!--/TMPL_IF-->
    <!--/TMPL_LOOP-->
  </div>
  <div id="find">
    <input
      id="find-text"
      type="text"
      maxlength="128"
      placeholder="Поиск по сайту"
    />
    <div id="find-go"></div>
  </div>
  <div id="header-status"></div>
  <div class="clr"></div>
</div>

main/templates/main/blocks/main.css.html
<style>
  #main-header {
    font-size: 95%;
  }
  #main-footer {
    font-size: 80%;
    color: #333333;
  }
</style>

main/templates/main/blocks/main.footer.html
<div id="main-intro">
  <div class="main-intro-sect">
    <h2>О компании «Профклимат»</h2>
    <p>
      На рынке Санкт-Петербурга довольно много фирм, которые специализируются на
      <b>продаже</b> и <b>установке кондиционеров</b>. Но найти
      интернет-магазин, в котором можно купить <b><i>кондиционер</i></b> по
      хорошей цене, с качественной установкой и
      <i>увеличенной гарантией</i> гораздо сложнее.
    </p>
    <p>
      «Профклимат» выполняет полный комплекс работ по проектированию, продаже,
      монтажу и обслуживанию систем кондиционирования, вентиляции и отопления
      бытовых и производственных помещений в Санкт-Петербурге.
    </p>
    <p>
      Мы предлагаем большой выбор современного климатическое оборудования с
      богатым спектром функциональных возможностей и широким диапазоном цен.
    </p>
  </div>
  <div class="main-intro-sect">
    <h2>Кондиционирование</h2>
    <p>
      Наша компания является официальным дилером ведущих мировых брендов.
      Климатическое оборудование таких компаний, как
      <b
        ><i
          >Mitsubishi Electric, Mitsubishi Heavy Industries, Daikin, LG,
          Panasonic, Toshiba, Fujitsu, Lessar, Hisense, Tosot, Ballu,
          Electrolux</i
        ></b
      >
      и др. Вы можете приобрести на нашем сайте.
    </p>
    <p>
      Удобная навигация и интеллектуальная система подбора позволят
      самостоятельно выбрать <b>кондиционер</b>, наиболее подходящий именно Вам.
    </p>
    <p>
      <b>Сплит-система</b> или <b>мобильный кондиционер</b> для дома и квартиры,
      <b>кассетный</b> или <b>канальный</b> для офиса и производства,
      <b>напольно-потолочный</b> для магазина. Подбор мощности по площади
      помещения и освещённости, сравнение выбранного оборудования по параметрам
      позволят Вам разобраться в тонкостях различных функций, предлагаемых
      производителями.
    </p>
    <p>
      Также Вы сможете понять, нужен ли вам <b>зимний комплект</b>, какой
      уровень шума является для Вас приемлемым и многое другое, прочитав
      подборку тематических материалов в разделе
      <a href="/pub" class="mlinks">«Статьи»</a> нашего сайта.
    </p>
    <p>
      Если же у Вас нет времени разбираться во всех тонкостях, Вы можете
      позвонить по номеру Компании и проконсультироваться со специалистом. Наши
      сотрудники с радостью помогут Вам в выборе кондиционера и выставят
      необходимое коммерческое предложение.
    </p>
    <p>
      Быстрое оформление заказа, гибкая ценовая политика, сезонные скидки на
      монтаж (например, установка бытовой сплит-системы в квартире стоит от 8100
      рублей). Гарантия на монтажные работы сроком до 5 лет (только на
      кондиционеры, купленные в нашей Компании).
    </p>
    <p>
      Делайте правильный выбор, а мы сделаем всё, чтобы Вы остались довольны. И
      новый кондиционер будет радовать Вас долгие годы.
    </p>
  </div>
  <div class="main-intro-sect">
    <h2>Вентиляция</h2>
    <p>
      Вентиляция — очень широкое понятие, которое включает в себя и простейшую
      естественную вентиляцию на Вашей кухне, и современные приточно-вытяжные
      установки.
    </p>
    <p>
      Современные вентиляционные системы могут выполнять ряд дополнительных
      функций — таких, как очистка, кондиционирование, увлажнение, подогрев
      воздуха.
    </p>
    <p>
      Компания «Профклимат» имеет большой опыт в проектировании и монтаже
      вентиляционных систем любой сложности.
    </p>
    <p>
      Вентиляция проектируется под конкретное помещение и чётко поставленную
      техническую задачу.
    </p>
    <p>
      В каталоге нашей Компании Вы можете найти широкий выбор мини
      вент-установок различной степени функциональности и разных ценовых
      категорий.
    </p>
    <p>Для квартир и частных домов мы предлагаем вам такие услуги, как:</p>
    <ul>
      <li>Врезка вентиляционных клапанов в существующие пластиковые окна.</li>
      <li>Врезка приточных клапанов в стены</li>
      <li>Монтаж приточно-вытяжных установок с рекуперацией тепла.</li>
      <li>Монтаж рекуператоров.</li>
      <li>Монтаж бриззеров.</li>
    </ul>
    <p>
      Также у нас можно купить <b>модульную вентиляцию</b> и
      <b>компоненты вентиляционных систем</b>,
      <b>вентиляторы бытовые и промышленные</b>,
      <b>клапаны регулирующие и противопожарные</b>, <b>датчики</b> и
      <b>термостаты</b>, <b>частотные преобразователи</b> и
      <b>устройства плавного пуска</b>.
    </p>
  </div>
  <div class="main-intro-sect">
    <h2>Тепловое оборудование</h2>
    <p>
      Компания Профклимат представляет тепловое оборудование таких хорошо
      зарекомендовавших себя производителей, как
      <b>De Dietrich, Electrolux, Royal Thermo, Zanussi, Noirot</b> различных
      типов.
    </p>
    <p>
      <b>Водяные</b> и <b>электрические тёплые полы</b>,
      <b>тепловые завесы</b> и <b>пушки</b>, <b>масляные</b> и
      <b>инфракрасные радиаторы</b>, <b>электрические камины</b> и
      <b>конвекторы</b> различных типов.
    </p>
    <p>
      <b>Твёрдотопливные</b> и <b>газовые котлы</b>, <b>радиаторы отопления</b>,
      <b>проточные водонагреватели</b>, <b>бойлеры прямого</b> и
      <b>косвенного нагрева</b>.
    </p>
    <p>Расходные материалы и инженерная сантехника.</p>
    <p>
      Всё это и многое другое мы предложим Вам по хорошей цене. Наши специалисты
      бесплатно привезут оборудование в пределах Санкт-Петербурга и качественно
      смонтируют его в Вашей квартире или в частном доме.
    </p>
    <p>
      На оборудование предоставляется гарантия, также мы производим
      постгарантийное облуживание.
    </p>
    <p>
      Укладка водяного тёплого пола, монтаж газового оборудования. Такие работы
      стоит доверять только профессионалам — нашим сертифицированным
      специалистам.
    </p>
  </div>
</div>

main/templates/main/blocks/navbar.html
{% load nav_tags %}

<nav id="navbar">
  <div class="navbar-item">
    <a href="/" class="navbar-item-current">Главная</a>
  </div>
  <div class="navbar-item" itemprop="name">
    <a href="{% url "kondicionery:kondicionery" %}" class="navbar-item-current">Кондиционеры</a>
    <div class="navbar-sublist-show">
      <div class="navbar-sublist">
        {% tag_categories as categories %}
        {% for el in categories %}
        <div class="navbar-subitem" itemprop="name">
          <a href="{% url "kondicionery:subitem" el.slug %}" itemprop="url" title="">{{el.name}}</a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="navbar-item" itemprop="name">
    <a href="{% url "obogrevateli:obogrevateli" %}" itemprop="url" title="">Обогреватели</a>
    <div class="navbar-sublist-show">
      <div class="navbar-sublist">
        {% tag_categories_heat as categories %}
        {% for el in categories %}
        <div class="navbar-subitem" itemprop="name">
          <a href="{% url "obogrevateli:subitem" el.slug %}" itemprop="url" title="">{{el.name}}</a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="navbar-item" itemprop="name">
    <a href="{% url "ventilyacia:ventilyacia" %}" itemprop="url" title="">Вентиляция</a>
    <div class="navbar-sublist-show">
      <div class="navbar-sublist">
        {% tag_categories_vent as categories %}
        {% for el in categories %}
          <div class="navbar-subitem" itemprop="name">
            <a href="/ventilyaciya/{{el.slug}}" itemprop="url" title="">{{el.name}}</a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% tag_categories_nav as navbar %}
  {% for el in navbar %}
  <div class="navbar-item" itemprop="name">
    <a href="{% url "main:nav" el.slug %}" itemprop="url" title="">{{el.name}}</a>
  </div>
  {% endfor %}
  <div class="clr"></div>
</nav>

main/templates/main/blocks/navbar2.html
{% load nav_tags %}

<nav id="navbar">
{% tag_categories_nav as navbar %}
  {% for nav in navbar %}
  <div class="navbar-item">
      <a href="{% if nav.slug == None %}
      {% url "main:home" %}
      {% elif nav.slug == 'kondicionery' %}
      {% url "kondicionery:index" %}
      {% elif nav.slug == 'obogrevateli' %}
      {% url "obogrevateli:index" %}
      {% elif nav.slug == 'ventilyaciya' %}
      {% url "ventilyacia:index" %}
      {% else %}
      {% url "main:nav" nav.slug %}
      {% endif %}" 
      {% if nav.slug == navbar_slug %}
      class="navbar-item-current"
      {% endif %}>{{nav.name}}
      </a>
      {% if nav.code == '1' %}
      <div class="navbar-sublist-show">
        <div class="navbar-sublist">
          {% tag_categories as categories %}
          {% for el in categories %}
          <div class="navbar-subitem" itemprop="name">
            <a href="{% url "kondicionery:subitem" el.slug %}" itemprop="url" title="">{{el.name}}</a>
          </div>
          {% endfor %}
        </div>
      </div>
      {% elif nav.code == '2' %}
      <div class="navbar-sublist-show">
        <div class="navbar-sublist">
          {% tag_categories_heat as categories %}
          {% for el in categories %}
          <div class="navbar-subitem" itemprop="name">
            <a href="{% url "obogrevateli:subitem" el.slug %}" itemprop="url" title="">{{el.name}}</a>
          </div>
          {% endfor %}
        </div>
      </div>
      {% elif nav.code == '3' %}
      <div class="navbar-sublist-show">
        <div class="navbar-sublist">
          {% tag_categories_vent as categories %}
          {% for el in categories %}
            <div class="navbar-subitem" itemprop="name">
              <a href="/ventilyaciya/{{el.slug}}" itemprop="url" title="">{{el.name}}</a>
            </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
  </div>
  {% endfor %}
  <div class="clr"></div>
</nav>