kondicionery/urls.py
from django.urls import path

from kondicionery import views

app_name = 'kondicionery'

urlpatterns = [
    path('', views.kondicionery, name='index'),
    path('<slug:category_slug>/', views.subitem, name='subitem'),
    path('/<slug:products_slug>/', views.cunit, name='cunit'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('<slug:navbar_slug>', views.navbar, name='nav'),
]

profclimatorg/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static

from profclimatorg import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('kondicionery/', include('kondicionery.urls', namespace='kondicionery')),
    path('ventilyaciya/', include('ventilyacia.urls', namespace='ventilyacia')),
    path('obogrevateli/', include('obogrevateli.urls', namespace='obogrevateli')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kondicionery/models.py
from django.db import models

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название') 
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True,verbose_name='Описание')
    title = models.CharField(max_length=150, unique=True, verbose_name='Титульник')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def more(self):
        if self.slug == 'rashodnye-materialy-dlya-kondicionerov' or 'zapchasti-k-kondicioneram':
            return 'ok'
        

class Compressor(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название') 
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'compress'
        verbose_name = 'Компрессор'
        verbose_name_plural = 'Компрессоры'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название') 
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True,verbose_name='Описание')
    img = models.ImageField(upload_to='prod_images', blank=True, null=True, verbose_name='Изображение')
    imgmore = models.FileField(upload_to='descpript_images', blank=True, null=True, verbose_name='Изображение под описание')
    spec = models.TextField(blank=True, null=True,verbose_name='Хар-ки')
    price = models.DecimalField(default=0, verbose_name='Цена', decimal_places=0, max_digits=10)
    discount = models.DecimalField(default=0, verbose_name='Скидка в процентах', decimal_places=0, max_digits=3)
    cooled = models.DecimalField(default=0, verbose_name='Охлаждение', decimal_places=1, max_digits=4)
    heater = models.DecimalField(default=0, verbose_name='Обогрев', decimal_places=1, max_digits=4)
    articul = models.DecimalField(default=0, verbose_name='Артикул', decimal_places=0, max_digits=4)
    square = models.IntegerField(default=0, verbose_name="Площадь охлаждения")
    compress = models.ForeignKey(to=Compressor, on_delete=models.PROTECT, verbose_name='Компрессор')
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name='Категория')
    

    class Meta:
        db_table = 'products'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name
    
class Manuf(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название') 
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'manuf'
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name

kondicionery/views.py
from django.shortcuts import render

from kondicionery.models import Categories, Products

# Create your views here.
def kondicionery(request):

    item = Products.objects.all()

    context = {
        'title' : 'Купить кондиционер в Санкт-Петербурге недорого | ПрофКлимат.',
        'item' : item,
    }
    return render(request, 'kondicionery/kondicionery.html', context)

def cunit(request, products_slug):

    prod = Products.objects.get(slug=products_slug)
    item = Products.objects.all()

    data = {
        'prod' : prod,
        'item' : item,
    }

    return render(request, 'kondicionery/cunit.html', data)

def subitem(request, category_slug):

    category = Categories.objects.get(slug=category_slug)

    data = {
        'category' : category,
    }

    return render(request, 'kondicionery/subitem.html', data)

kondicionery/templates/blocks/cunits-filter-small.html
<fieldset>
  <legend>Фильтр</legend>

  <div style="margin-top: 0.2em"></div>
  <div id="units-filter-price" class="filter-box">
    Цена (руб): от от
    <input
      id="units-filter-price-min"
      type="number"
      min="4500"
      max="4600"
      value="0"
      step="any"
    />
    до
    <input
      id="units-filter-price-max"
      type="number"
      min="4500"
      max="4600"
      value="300000"
      step="any"
    />
    <div
      id="units-filter-price-slider"
      style="margin: 0.5em"
      class="slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"
      aria-disabled="false"
    >
      <div
        style="width: 0%"
        class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min"
      ></div>
      <a
        style="left: 0%"
        class="ui-slider-handle ui-state-default ui-corner-all"
        href="#"
      ></a>
      <div
        class="ui-slider-range ui-widget-header ui-corner-all"
        style="left: 0%; width: 100%"
      ></div>
      <a
        class="ui-slider-handle ui-state-default ui-corner-all"
        href="#"
        style="left: 100%"
      ></a>
    </div>
  </div>
  <div id="units-filter-cmd">
    <div
      class="units-filter-btn"
      id="units-filter-use"
      title="Применить условия отбора"
    >
      <span class="typcn typcn-arrow-forward"></span> Применить
    </div>
    <div
      class="units-filter-btn"
      id="units-filter-clear"
      title="Сбросить условия отбора"
    >
      <span class="typcn typcn-arrow-back"></span> Сбросить
    </div>
  </div>
  <div id="units-filter-opts" class="filter-box"></div>
</fieldset>

kondicionery/templates/blocks/cunits-footer.html
<p>Наши преимущества:</p>
<ul>
  <li>
    Компания «ПрофКлимат СПб» является официальным дилером ведущих мировых
    брэндов.
  </li>
  <li>
    У нас вы можете купить оборудование по честной цене, с качественной
    установкой и увеличенной гарантией.
  </li>
  <li>Быстрое оформление заказа, гибкая ценовая политика, скидки на монтаж.</li>
  <li>
    Наиболее ответственные работы выполнят сертифицированные специалисты,
    имеющие все необходимые документы.
  </li>
</ul>
<p>
  Также в нашей компании вы можете купить
  <a href="/obogrevateli/konvektor">конвекторы</a>,
  <a href="/obogrevateli/teploventilyator">тепловентиляторы</a>,
  <a href="/ventilyaciya/vozduxovody/gibkie">гибкие воздуховоды</a>.
</p>

kondicionery/templates/blocks/cunits_items.html
<div id="cunits-list">
  <input id="req-manufacturer" name="req-manufacturer" type="hidden" value=""/>
  <input id="req-utype" name="req-utype" type="hidden" value="" />
  <input id="req-btype" name="req-btype" type="hidden" value="" />
  <input id="req-format" name="req-format" type="hidden" value="tile"/>
  <input id="req-pgsize" name="req-pgsize" type="hidden" value="15"/>
  <input id="req-pgno" name="req-pgno" type="hidden" value="1" />
  <input id="req-sort" name="req-sort" type="hidden" value="rd" />
  <input id="req-photo" name="req-photo" type="hidden" value="1" />
  <input id="req-color" name="req-color" type="hidden" value="" />
  <input id="pg_count" name="pg_count" type="hidden" value="52" />
  <input id="d1r" name="d1r" type="hidden" value="91.3336" />
  <input id="price-min" name="price-min" type="hidden" value="18500"/>
  <input id="price-max" name="price-max" type="hidden" value="519300"/>
  <input id="service_area-min" name="service_area-min" type="hidden" value="9999"/>
  <input id="service_area-max" name="service_area-max" type="hidden" value="0"/>
  <input id="noise_level-min" name="noise_level-min" type="hidden" value="999"/>
  <input id="noise_level-max" name="noise_level-max" type="hidden" value="0"/>
  <input id="power_cooling-min" name="power_cooling-min" type="hidden" value="1.3"/>
  <input id="power_cooling-max" name="power_cooling-max" type="hidden" value="28.1"/>
  <input id="power_heating-min" name="power_heating-min" type="hidden" value="0.0"/>
  <input id="power_heating-max" name="power_heating-max" type="hidden" value="31.1"/>
  <input id="req_inv" name="req_inv" type="hidden" value="3" />
  <input id="req_price-min" name="req_price-min" type="hidden" value="18500"/>
  <input id="req_price-max" name="req_price-max" type="hidden" value="519300"/>
  <input id="req_service_area-min" name="req_service_area-min" type="hidden" value="0"/>
  <input id="req_service_area-max" name="req_service_area-max" type="hidden" value="9999999"/>
  <input id="req_noise_level-min" name="req_noise_level-min" type="hidden" value="0"/>
  <input id="req_noise_level-max" name="req_noise_level-max" type="hidden" value="999"/>
  <input id="req_power_cooling-min" name="req_power_cooling-min" type="hidden" value="1.3"/>
  <input id="req_power_cooling-max" name="req_power_cooling-max" type="hidden" value="28.1"/>
  <input id="req_power_heating-min" name="req_power_heating-min" type="hidden" value="0.0"/>
  <input id="req_power_heating-max" name="req_power_heating-max" type="hidden" value="31.1"/>
<div id="cunits-list-items">
    {% for prod in item %}
    <div class="units-item">
        <div class="units-item-desc">
        <span class="unit-item-select"><a href="{% url "kondicionery:cunit" prod.slug %}" title="Перейти к описанию">{{ prod.name }}</a></span>
        </div>
        <div class="units-item-spec">
        <div class="units-item-spec-attr">
        <span class="val-cold-power"></span>{{ prod.cooled }}
        </div>
        
        <div class="units-item-spec-attr">
        <span class="val-heat-power"></span>{{ prod.heater }}
        </div>
        
        
        <div class="units-item-spec-attr">Компрессор: {{prod.compress}}</div>
        
        <div class="units-item-spec-attr">
        <span class="val-cold-area help" title="Для средней освещенности и высоты потолка 2,7м"></span>{{prod.square}}
        </div>
        </div>
        
        <div class="units-item-thumbnail">
          {% if prod.img %}
            <a href="{% url "kondicionery:cunit" prod.slug %}" title="Перейти к описанию"><img src="{{prod.img.url}}" alt="{{prod.name}}" class="units-item-img"></a>
          {% endif %}
        </div>
        
        <div class="units-item-article">{{prod.articul}}</div>
        <div class="units-item-price"><span class="units-item-pfx">цена</span>{{ prod.price }}<span class="val-currency"></span></div>
        <div class="units-item-buy" title="{{prod.name}}" data-group="cu" data-key="/kondicionery/ballu-split-sistema-nastennyj-bso-09hn1_20y" data-title="{{prod.name}}" data-rub="{{prod.price}}">Купить</div>
    </div>
    {% endfor %}
</div>

kondicionery/templates/blocks/cunits_recipe.html
{% load static %}

<div id="cunits-recipe">
  <a class="recipe" href="/kondicionery/dlya-kvartiry">
    <img src="{% static "/images/recipe/01kvart.png" %}" alt="Для квартиры" />
    <h3>Для квартиры</h3>
  </a>
  <a class="recipe" href="/kondicionery/dlya-doma-dachi-kottedzha">
    <img src="{% static "/images/recipe/01dom.png" %}" alt="Для дома, дачи,
    коттеджа" />
    <h3>Для дома, дачи, коттеджа</h3>
  </a>
  <a class="recipe" href="/kondicionery/dlya-kafe-magazina">
    <img src="{% static "/images/recipe/01kafe.png" %}" alt="Для кафе, магазина"
    />
    <h3>Для кафе, магазина</h3>
  </a>
  <a class="recipe" href="/kondicionery/dlya-ofisa">
    <img src="{% static "/images/recipe/01office.png" %}" alt="Для офиса" />
    <h3>Для офиса</h3>
  </a>
  <a class="recipe" href="/kondicionery/dlya-proizvodstvennyh-pomeshchenij ">
    <img src="{% static "/images/recipe/01prod.png" %}" alt="Для
    производственных помещений" />
    <h3>Для производственных помещений</h3>
  </a>
  <a class="recipe" href="/kondicionery/dlya-servernyh">
    <img src="{% static "/images/recipe/01serv.png" %}" alt="Для серверных" />
    <h3>Для серверных</h3>
  </a>
  <div class="clr"></div>
</div>

kondicionery/templates/blocks/cunits_toolbar_left.html
  <h1 itemprop="headline">{{category.name}}</h1>
  <div
    id="navbar-path"
    itemscope=""
    itemtype="http://schema.org/BreadcrumbList"
  >
    <span
      itemprop="itemListElement"
      itemscope=""
      itemtype="http://schema.org/ListItem"
      ><a class="breadcrumbs" itemprop="item" href="/"
        ><span itemprop="name">Главная</span></a
      ><meta itemprop="position" content="1" /></span
    ><span class="breadcrumbs_sep"></span
    ><span
      itemprop="itemListElement"
      itemscope=""
      itemtype="http://schema.org/ListItem"
      ><a class="breadcrumbs" itemprop="item" href="/kondicionery"
        ><span itemprop="name">Кондиционеры</span></a
      ><meta itemprop="position" content="2" /></span
    ><span class="breadcrumbs_sep"></span
    ><span
      itemprop="itemListElement"
      itemscope=""
      itemtype="http://schema.org/ListItem"
      ><a class="breadcrumbs" itemprop="item" href="/kondicionery/{{category.slug}}"
        ><span itemprop="name">{{category.name}}</span></a
      ><meta itemprop="position" content="3"
    /></span>
  </div>

kondicionery/templates/blocks/cunits_toolbar_right.html
<!-- units-toolbar.html begin -->
<div
  class="unit-list-button"
  id="units-filter-hide"
  title="Скрыть панель фильтров"
  style="display: inline-block"
>
  Скрыть фильтры
</div>
<div
  class="unit-list-button"
  id="units-filter-show"
  title="Показать панель фильтров"
  style="display: none"
>
  Показать фильтры
</div>
<div
  id="units-toolbar-sort-menu"
  class="unit-list-popup-opt"
  style="display: none"
>
  <!--div data-value="rd">Без сортировки</div-->
  <div data-value="ma">Сортировка: по производителю</div>
  <div data-value="pa">Сортировка: по цене - сначала недорогие</div>
  <div data-value="pd">Сортировка: по цене - сначала дорогие</div>
  <!-- div data-value="dd">Сортировка: по новизне</div -->
  <!-- div data-value="sd">Сортировка: по популярности</div -->
</div>
<div
  id="units-toolbar-psize-menu"
  class="unit-list-popup-opt"
  style="display: none"
>
  <div data-value="10">Показывать по 10</div>
  <div data-value="15">Показывать по 15</div>
  <div data-value="30">Показывать по 30</div>
  <div data-value="50">Показывать по 50</div>
  <div data-value="999999">Показывать все</div>
</div>
<div
  class="unit-list-popup"
  data-value="15"
  data-list="units-toolbar-psize-menu"
  id="units-toolbar-psize"
>
  Показывать по 15
</div>
<div
  class="unit-list-popup"
  data-value="rd"
  data-list="units-toolbar-sort-menu"
  id="units-toolbar-sort"
>
  Сортировать по
</div>
<a
  class="unit-list-button unit-list-button-off"
  id="units-toolbar-show-table"
  style="font-size: 18pt"
  title="Подробная форма"
  href="?f=table"
  ><span class="typcn typcn-th-list-outline"></span
></a>
<a
  class="unit-list-button"
  id="units-toolbar-show-tile"
  style="font-size: 18pt"
  title="Краткая форма"
  href="?f=tile"
  ><span class="typcn typcn-th-small-outline"></span
></a>
<a
  class="unit-list-button"
  id="units-toolbar-refresh"
  style="font-size: 18pt"
  title="Обновить"
  href=""
  ><span class="typcn typcn-arrow-sync"></span
></a>
<!-- units-toolbar.html end -->